### ISSUE TITLE
Java 17 Build Errors

### ISSUE THREAD

**Issue by Ryan-nd** [synthetichealth/synthea#1212]
### What happened?

Hello,

Just wanted to ask for changing my Synthea version from 3.1.1 to 3.0.0, do I just download the highlighted files(Picture), as I had an End-to-End Error when building the Synthea in version 3.1.1. Would real appreciate the help!
<img width="679" alt="synthea installation 2" src="https://user-images.githubusercontent.com/85671367/204534516-52bac52f-64ec-48e8-92cf-365b9b7d759a.png">

### Environment

```markdown
- OS:
- Java:
```

**Comment by hadleynet** [comment]
If you just want to run Synthea then you only need the synthea-with-dependencies.jar file. If you want to recompile from source then the source code ZIP file should have everything you need. If you already cloned the repo with git then you can just `git checkout v3.0.0` to switch to that version.

All that said, would it be worth trying to figure out the issue preventing you from building the latest code? Can you post the output from the build log that shows the error you encountered?

**Comment by Ryan-nd** [comment]
Hi Hadley,

We did try to figure out on different Mac, Linux & Windows to see the different issues by looking at the reports generated. The report states its about the Entity-Manager file. ( End-to-End error), have attached the picture for your reference! 
<img width="552" alt="synthea installation" src="https://user-images.githubusercontent.com/85671367/204701886-4f1f5938-6700-4422-aec3-ba9c1a566968.png">
<img width="845" alt="synthea installation 3" src="https://user-images.githubusercontent.com/85671367/204701922-268499e4-a9eb-4a73-bb2f-d726d9b2109e.png">

**Comment by Ryan-nd** [comment]
Also, I've ran into another issue after installing Synthea v3.0.0 it states how unsupported class file major version 61, I'm thinking it is the  'synthea-with-dependencies.jar file' does not support my Java version 17, would u know where I can find the Java version that supports the JAR file. Real Appreciate again for the insights given!

Regards,
Ryan Li

**Comment by Ryan-nd** [comment]
I'm currently running on Gradle 7.0.2, Java 17.
<img width="857" alt="synthea installation 4" src="https://user-images.githubusercontent.com/85671367/204707546-c73bcbb7-207b-4664-bb52-06e86eec59b6.png">

**Comment by jawalonoski** [comment]
Do you have multiple versions of Java on your machine(s)?

Java 17 compiles into class files with major version 61... if you try to run your class files with an earlier version of Java than you used to compile it (e.g., running with Java 16 when you compiled with Java. 17) you'll get that error.

**Comment by r0sies** [comment]
I'm experiencing the same thing.
I went to upgrade synthea, now the latest and 3.0.0 versions aren't working.
Windows 11
Gradle 7.3.3
Java 17.0.5

With the latest version:
org.mitre.synthea.identity.EntityManagerTest > endToEnd FAILED
    java.nio.file.NoSuchFileException: C:\Users\rosem\AppData\Local\Temp\junit16014707406191775577\junit1409570970771518193\json
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
 
With 3.0.0
Unsupported class file major version 61

**Comment by Ryan-nd** [comment]
> Do you have multiple versions of Java on your machine(s)?
> 
> Java 17 compiles into class files with major version 61... if you try to run your class files with an earlier version of Java than you used to compile it (e.g., running with Java 16 when you compiled with Java. 17) you'll get that error.

Hi Jason,
Thanks for the quick response.
Nope I do not have multiple versions of Java, only Java 17.0.5.

**Comment by jawalonoski** [comment]
There are actually multiple issues in this thread, and it is hard to disentangle them.

If you are having problems with the current build, and reverted to `v3.0.0`, to get Java 17 to build the project in Windows you need to make the following changes (which are already fixed in newer versions):

- `build.gradle` - change jacoco to use `0.8.7`
```
jacoco {
  toolVersion '0.8.7'
}
```
- `.\gradle\wrapper\gradle-wrapper.properties` change the gradle distribution
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
```
- `./gradlew clean check`

**Comment by jawalonoski** [comment]
The Java 17 build on Windows using the latest code in `master` should be fixed with #1215... can someone on Windows verify or refute?

**Comment by Ryan-nd** [comment]
Hi Jason,

Will do as communicated. Thanks for the quick response!

Regards,
Ryan

**Comment by Ryan-nd** [comment]
> The Java 17 build on Windows using the latest code in `master` should be fixed with #1215... can someone on Windows verify or refute?

Downloaded the Master branch that was updated. However, still the same issue with using Java 17.0.5. Attached the pic for reference.
<img width="846" alt="synthea installation 2" src="https://user-images.githubusercontent.com/85671367/205426241-3fb26b90-a182-4848-8054-c8f1fdb90078.png">

**Comment by dehall** [comment]
@Ryan-nd I'm not able to reproduce this issue, but I wonder if the changes made for 1215 may have been a red herring. If for some reason the JSON exporter failed to write JSON then the folder referenced won't exist. Can you try a couple things for us to help us debug this?

1. Confirm you have no other changes made to the synthea code.
2. In the file `build.gradle` - there is a "test" section starting on line 136 with a few lines commented out (starting with `//`). Can you remove the "//" in front of these 4 lines?
```
    showExceptions = true
    showCauses = true
    showStackTraces = true
    showStandardStreams = true
```
3. Finally re-run the test suite. You can re-run just this one test with `.\gradlew.bat test --tests org.mitre.synthea.identity.EntityManagerTest` . If it turns out that running just this one test at a time makes it run successfully, there may be some sequence that you are hitting that creates an invalid setting somewhere that causes this test to fail. It's rare but we've seen that happen before. With the changes above then it should print out a lot more and hopefully give us some clues as to what went wrong.

**Comment by Ryan-nd** [comment]
Hi dehall, I've made the changes as stated in build.gradle and reinstalled Java as a whole and it builds successfully with no error.

**Comment by dehall** [comment]
Great thanks @Ryan-nd . Also I should have looked closer at your earlier comments in this issue - based on the image you posted a while ago I've done some more digging into this issue so thank you for sharing that. It seems like this error is transient, based on time zone and time of day, and I hope to push a permanent fix shortly.

**Comment by Ryan-nd** [comment]
Alright, thanks @dehall ! No worries at all. And also, could I ask more details about Synthea as I'm trying to create data that has more pax in the population having breast cancer, would there be a way to alter it by changing the breast_cancer module?

**Comment by dehall** [comment]
Yes you can do that. This prior discussion describes the basic process of modifying the modules: https://github.com/synthetichealth/synthea/discussions/1060  and the breast cancer module can be viewed/edited here https://synthetichealth.github.io/module-builder/#breast_cancer
And we're happy to provide more guidance if needed, but if so please open a separate discussion for that.

**Comment by Ryan-nd** [comment]
@dehall Alright, thanks! Appreciate the helps and insights given!

Regards,
Ryan

**Comment by r0sies** [comment]
Hi Dylan,
I have just rebuilt Synthea and can confirm it completed without any errors (for me at least). Thank you!
