### ISSUE TITLE
NullPointerException error

### ISSUE THREAD

**Issue by naomizoe** [synthetichealth/synthea#734]
Hi team,

I have created my own module using the module builder and downloaded the JSON file.
Next, I tried to pass it to Synthea:

C:\Users\naomi\Documents>java -jar synthea-with-dependencies.jar -d modules

However, I can see it scans my local module but I get the following error and no output:

java.lang.NullPointerException
        at org.mitre.synthea.engine.Module.lambda$null$2(Module.java:90)
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:344)
        at org.mitre.synthea.engine.Module.lambda$getModules$5(Module.java:170)
        at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
        at org.mitre.synthea.engine.Module.getModules(Module.java:166)
        at org.mitre.synthea.engine.Generator.init(Generator.java:214)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:143)
        at App.main(App.java:144)
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:354)
        at org.mitre.synthea.engine.Module.lambda$getModules$5(Module.java:170)
        at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
        at org.mitre.synthea.engine.Module.getModules(Module.java:166)
        at org.mitre.synthea.engine.Generator.init(Generator.java:214)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:143)
        at App.main(App.java:144)
Caused by: java.lang.NullPointerException
        at org.mitre.synthea.engine.Module.lambda$null$2(Module.java:90)
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:344)
        ... 6 more

Any idea how to fix this?

Edit: the same error occurs when I save the examplitis JSON file locally and try to pass it to Synthea.

thanks in advance,
Naomi

**Comment by hadleynet** [comment]
Thanks for the error report. Based on the stack trace we've identified that the automated build of the synthea-with-dependencies.jar is not working as expected and the current version is from back on November 2019. Would you be able to try the alternate developer getting started instructions while we try to track this down:

https://github.com/synthetichealth/synthea/wiki/Developer-Setup-and-Running

**Comment by hadleynet** [comment]
We have fixed the automated build of synthea-with-dependencies.jar. Could you retry using the following version:

https://github.com/synthetichealth/synthea/releases/download/master-branch-latest/synthea-with-dependencies.jar

Thanks,
Marc.

**Comment by XcrigX** [comment]
Funny, I just hit the same problem. I tried the updated jar file Marc, no luck. 
I placed a file called chf_100.json in a subdir called "mods". 

It sees the file in my mods dir, but still throws the error. 
I've tried a few variations, but the error is always the same:
java -Xmx1G -jar synthea-with-dependencies.jar -p 10 -d ./mods
java -Xmx1G -jar synthea-with-dependencies.jar -p 10 -d C:\temp\synthea\mods
java -Xmx1G -jar synthea-with-dependencies.jar -p 10 -d C:\\temp\\synthea\\mods
java -Xmx1G -jar synthea-with-dependencies.jar -p 10 -d C:\temp\synthea\mods\
java -Xmx1G -jar synthea-with-dependencies.jar -p 10 -d C:\\temp\\synthea\\mods\\


Exec with: 
java -Xmx1G -jar synthea-with-dependencies.jar -p 10 -d ./mods


Scanned 61 modules and 55 submodules.
Scanned 1 local modules and 0 local submodules.
...
Loading submodule modules/breast_cancer/chemotherapy_breast.json
Loading module modules/opioid_addiction.json
Loading module mods\chf_100.json
java.lang.IllegalArgumentException: resource mods\chf_100.json not found.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
        at com.google.common.io.Resources.getResource(Resources.java:195)
        at org.mitre.synthea.helpers.Utilities.readResource(Utilities.java:310)
        at org.mitre.synthea.engine.Module.loadFile(Module.java:179)
        at org.mitre.synthea.engine.Module.lambda$null$0(Module.java:120)
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:407)
        at org.mitre.synthea.engine.Module.lambda$getModules$4(Module.java:228)
        at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
        at org.mitre.synthea.engine.Module.getModules(Module.java:224)
        at org.mitre.synthea.engine.Generator.init(Generator.java:241)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:171)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:155)
        at App.main(App.java:188)
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: resource mods\chf_100.json not found.
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:417)
        at org.mitre.synthea.engine.Module.lambda$getModules$4(Module.java:228)
        at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
        at org.mitre.synthea.engine.Module.getModules(Module.java:224)
        at org.mitre.synthea.engine.Generator.init(Generator.java:241)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:171)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:155)
        at App.main(App.java:188)
Caused by: java.lang.IllegalArgumentException: resource mods\chf_100.json not found.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
        at com.google.common.io.Resources.getResource(Resources.java:195)
        at org.mitre.synthea.helpers.Utilities.readResource(Utilities.java:310)
        at org.mitre.synthea.engine.Module.loadFile(Module.java:179)
        at org.mitre.synthea.engine.Module.lambda$null$0(Module.java:120)
        at org.mitre.synthea.engine.Module$ModuleSupplier.get(Module.java:407)
        ... 7 more

**Comment by XcrigX** [comment]
I think the problem has something to do with how the paths are being relativized in Module.walkModuleTree. And then Utilities.readResource is using Resources.getResources() to which as best I can tell will only find classpath resources. 
I'm trying to see if I can find a simple fix, but not being familiar with the code so far nothing is obvious.  Anyway thought I'd report in with my finding so far.

**Comment by naomizoe** [comment]
Unfortunately same for me. Getting the same error with the updated jar file.

**Comment by hadleynet** [comment]
Thanks. I can reproduce this locally, working on a fix.

**Comment by hadleynet** [comment]
I've pushed a fix that works on a Mac to a new branch: https://github.com/synthetichealth/synthea/tree/local-module-fix

If one of you is able to test it on Windows that would be very helpful.

**Comment by XcrigX** [comment]
Confirmed. Running with an absolute path such as this works: 
 -d C:\temp\synthea\mods\
I also tried a relative path which also worked:
 -d  ..\mods\

Thanks.
